name: Test

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Dependencies
        run: mvn dependency:resolve
      
      - name: Run tests
        run: mvn test
